backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

local_backend: true
media_folder: "content/posts"
public_folder: "./"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/"
    create: true
    slug: "{{slug}}" 
    path: "{{slug}}/index"
    fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Excerpt", name: "excerpt", widget: "text" }
        - { label: "Featured Image", name: "featuredImage", widget: image }
        - { label: "Date", name: "date", widget: "datetime" }
        - { label: "Tags", name: "tags", widget: "list" }
        - { label: "Body", name: "body", widget: "markdown" }